recording:
  width: 1280
  height: 720
  margin: 5
  maximum_chunk_length: 60
  maximum_chunk_count: 1
  maximum_video_length: 120
  maximum_recording_time: 1800
  maximum_idle_time: 300
  motion_detection:
    interval: 5
    threshold: 0
    minimum_area: 0.0002
# composing:
#   maximum_video_length: 30
  # shortening:
  #   threshold: 64
  #   minimum_area: 0.00005
  # perspective_correction:
  #   left_top_x: 0
  #   left_top_y: 0
  #   right_top_x: 1280
  #   right_top_y: 0
  #   right_bottom_x: 1280
  #   right_bottom_y: 720
  #   left_bottom_x: 0
  #   left_bottom_y: 720
publishing:
  # dropbox_path: "profilowka/output/"
  delete_local: false
  format: "h264"
training:
  storage_path: "tmp/training_data"
  glipse_width: 96
  glipse_height: 96
  sample_width: 28
  sample_height: 28
  crop_factor: 0.87
  grayscale: false
